### ISSUE TITLE
Error when running varnish plugin

### ISSUE THREAD

**Issue by solocommand** [threelegs/newrelic-plugins#18]
I get the following error when trying to run the varnish plugin:

```
[solocommand@app1 newrelic_3legs_plugin-0.0.2]$ java -jar newrelic_3legs_plugin-0.0.2.jar
INFO: Using configuration file /home/solocommand/newrelic_3legs_plugin-0.0.2/config/newrelic.properties
INFO: New Relic monitor started
[Fatal Error] :1:1: Premature end of file.
org.xml.sax.SAXParseException: Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:242)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:286)
    at ar.com.threelegs.newrelic.cassandra.Varnish.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
pushing 0 metrics...
done!
```

My application.conf:

```
varnish = [
    {
        name = edge1
        user = solocommand
        host = edge1.mydomain.com
    }
],
```

Any idea what might be causing this and how I can troubleshoot further?

**Comment by kimegede** [comment]
I did a `ls /var/lib/varnish/` to get my `instance` name. Some better info here would be nice!

**Comment by sanantharaman11** [comment]
Hope its ok to reopen this issue.. I'm stuck at the same step. varnish and plugin on the same machine and I am not able to get the plugin up and running. Below is how plugin.json looks. Tried all combinations on this post as in adding host,user,instance etc. varnishstat -1 -x -n default output is Cannot open /var/lib/varnish/default/_.vsm: No such file or directory. I'm trying to start using npi and the deamon.log output looks like 'Executing 'varnishstat -1 -x' failed: Premature end of file' ..any help appreciated!

{
  "agents": [
    {
      "type": "varnish",
      "name": "My Varnish Agent"
    }
  ],
