### ISSUE TITLE
Varnish Plugin does not seem to report

### ISSUE THREAD

**Issue by Pcummings** [threelegs/newrelic-plugins#38]
Hey Guys,

Just setting up our new infrastructure and I would love to see some varnish data in newrelic. Everything is up and running however I get no information back into newrelic, I note that I'm not the only one having this issue - any updates on it?

I'm on Varnish 4, ubuntu 14.04 and plugin version 2.0.0

**Comment by jbethmont** [comment]
Hey guys,

I'm having the same issue. The agent logs show this:

ERROR com.newrelic.metrics.publish.binding.Request - An error occurred communicating with the New Relic service
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_65]
	at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_65]
	at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_65]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442) ~[na:1.7.0_65]
	at sun.security.ssl.InputRecord.read(InputRecord.java:480) ~[na:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927) ~[na:1.7.0_65]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:884) ~[na:1.7.0_65]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102) ~[na:1.7.0_65]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[na:1.7.0_65]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) ~[na:1.7.0_65]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[na:1.7.0_65]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687) ~[na:1.7.0_65]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633) ~[na:1.7.0_65]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323) ~[na:1.7.0_65]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468) ~[na:1.7.0_65]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.7.0_65]
	at com.newrelic.metrics.publish.binding.Request.processResponse(Request.java:149) ~[plugin.jar:2.0.0 April 10 2014]
	at com.newrelic.metrics.publish.binding.Request.deliver(Request.java:115) ~[plugin.jar:2.0.0 April 10 2014]
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:203) [plugin.jar:2.0.0 April 10 2014]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_65]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]

**Comment by jbethmont** [comment]
It's seems to be related to Varnish 4.

**Comment by Pcummings** [comment]
Yeah I'm on 4.0.2 and nothing is getting reported to newrelic

**Comment by audvin** [comment]
Can confirm that this plugin doesn't support Varnish 4.

**Comment by juanformoso** [comment]
@audvin I'm not actively supporting this anymore. Feel free to fork the repo and continue it, or ask for help in the community forums at https://discuss.newrelic.com/

**Comment by craigcarnell** [comment]
Has anyone found a Varnish 4.0 fork of this? Thanks

**Comment by audvin** [comment]
@craigcarnell I've not found anything yet...New Relic was going to look around, but I've heard nothing back. Perhaps check with them?

**Comment by dh-harald** [comment]
@juanformoso: can you share somehow your plugin's default dashboard? I try to fix your plugin into varnish 4.0... Thanks!
