### ISSUE TITLE
unable to run the plugin.jar file

### ISSUE THREAD

**Issue by vamzz1** [threelegs/newrelic-plugins#52]
When i'm trying to run the plugin.jar i am getting these errors.
FYI: i opened the endpoints required by the plugin for the host.

INFO: Using configuration file /newrelic_3legs_plugin-2.0.0/config/newrelic.json
INFO: Using configuration file /newrelic_3legs_plugin-2.0.0/config/plugin.json
INFO: New Relic monitor started
[2016-04-25 18:50:19,573] ERROR ar.com.threelegs.newrelic.CassandraRing -
ar.com.threelegs.newrelic.jmx.ConnectionException: unable to connect to 100.75.152.74
        at ar.com.threelegs.newrelic.jmx.JMXHelper.run(Unknown Source) ~[plugin.jar:2.0.0 April 10 2014]
        at ar.com.threelegs.newrelic.util.CassandraHelper.getRingHosts(Unknown Source) ~[plugin.jar:2.0.0 April 10 2014]
        at ar.com.threelegs.newrelic.CassandraRing.pollCycle(Unknown Source) [plugin.jar:2.0.0 April 10 2014]
        at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:199) [plugin.jar:2.0.0 April 10 2014]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 100.75.152.74; nested exception is:
        java.net.ConnectException: Connection refused]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369) ~[na:1.8.0_72]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_72]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[na:1.8.0_72]
        ... 11 common frames omitted
Caused by: javax.naming.ServiceUnavailableException: null
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:122) ~[na:1.8.0_72]
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205) ~[na:1.8.0_72]
        at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[na:1.8.0_72]
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955) ~[na:1.8.0_72]
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922) ~[na:1.8.0_72]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287) ~[na:1.8.0_72]
        ... 13 common frames omitted
Caused by: java.rmi.ConnectException: Connection refused to host: 100.75.152.74; nested exception is:
        java.net.ConnectException: Connection refused
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_72]
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_72]
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_72]
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342) ~[na:1.8.0_72]
        at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source) ~[na:1.8.0_72]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:118) ~[na:1.8.0_72]
        ... 18 common frames omitted

**Comment by nothau** [comment]
see https://github.com/threelegs/newrelic-plugins/issues/53 for a solution
